/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const AdminSession = IDL.Record({
  'token' : IDL.Text,
  'username' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TeamId = IDL.Nat;
export const Timestamp = IDL.Int;
export const FixtureId = IDL.Nat;
export const MatchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const Fixture = IDL.Record({
  'id' : FixtureId,
  'status' : MatchStatus,
  'awayTeamId' : TeamId,
  'homeTeamId' : TeamId,
  'kickoff' : Timestamp,
  'homeGoals' : IDL.Opt(IDL.Nat),
  'matchday' : IDL.Nat,
  'awayGoals' : IDL.Opt(IDL.Nat),
});
export const AdminError = IDL.Variant({
  'invalidInput' : IDL.Text,
  'notAuthenticated' : IDL.Null,
  'notFound' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : Fixture, 'err' : AdminError });
export const KnockoutRound = IDL.Variant({
  'final' : IDL.Null,
  'quarterFinal' : IDL.Null,
  'roundOf16' : IDL.Null,
  'semiFinal' : IDL.Null,
});
export const TieId = IDL.Nat;
export const KnockoutTie = IDL.Record({
  'id' : TieId,
  'homePenalties' : IDL.Opt(IDL.Nat),
  'awayTeamId' : IDL.Opt(TeamId),
  'slot' : IDL.Nat,
  'awayPenalties' : IDL.Opt(IDL.Nat),
  'homeTeamId' : IDL.Opt(TeamId),
  'homeGoals' : IDL.Opt(IDL.Nat),
  'winnerTeamId' : IDL.Opt(TeamId),
  'awayGoals' : IDL.Opt(IDL.Nat),
  'round' : KnockoutRound,
});
export const Result_3 = IDL.Variant({ 'ok' : KnockoutTie, 'err' : AdminError });
export const Team = IDL.Record({
  'id' : TeamId,
  'name' : IDL.Text,
  'crestUrl' : IDL.Opt(IDL.Text),
  'shortCode' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : Team, 'err' : AdminError });
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AdminError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(Fixture),
  'err' : AdminError,
});
export const TieView = IDL.Record({
  'id' : TieId,
  'homePenalties' : IDL.Opt(IDL.Nat),
  'slot' : IDL.Nat,
  'awayTeamName' : IDL.Opt(IDL.Text),
  'awayPenalties' : IDL.Opt(IDL.Nat),
  'winnerTeamName' : IDL.Opt(IDL.Text),
  'homeTeamName' : IDL.Opt(IDL.Text),
  'homeGoals' : IDL.Opt(IDL.Nat),
  'awayGoals' : IDL.Opt(IDL.Nat),
  'round' : KnockoutRound,
});
export const BracketRoundView = IDL.Record({
  'ties' : IDL.Vec(TieView),
  'round' : KnockoutRound,
});
export const LeagueRow = IDL.Record({
  'won' : IDL.Nat,
  'teamName' : IDL.Text,
  'goalDifference' : IDL.Int,
  'played' : IDL.Nat,
  'lost' : IDL.Nat,
  'goalsFor' : IDL.Nat,
  'shortCode' : IDL.Text,
  'goalsAgainst' : IDL.Nat,
  'teamId' : TeamId,
  'drawn' : IDL.Nat,
  'points' : IDL.Nat,
});
export const MatchView = IDL.Record({
  'id' : FixtureId,
  'status' : MatchStatus,
  'awayTeamName' : IDL.Text,
  'homeTeamName' : IDL.Text,
  'kickoff' : Timestamp,
  'homeGoals' : IDL.Opt(IDL.Nat),
  'matchday' : IDL.Nat,
  'awayGoals' : IDL.Opt(IDL.Nat),
});
export const TournamentState = IDL.Record({
  'tournamentName' : IDL.Text,
  'stageLabel' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_5], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(AdminSession)], []),
  'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFixture' : IDL.Func(
      [IDL.Text, TeamId, TeamId, IDL.Nat, Timestamp],
      [Result_1],
      [],
    ),
  'createKnockoutTie' : IDL.Func(
      [IDL.Text, KnockoutRound, IDL.Nat, IDL.Opt(TeamId), IDL.Opt(TeamId)],
      [Result_3],
      [],
    ),
  'createTeam' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'deleteFixture' : IDL.Func([IDL.Text, FixtureId], [Result_2], []),
  'deleteKnockoutTie' : IDL.Func([IDL.Text, TieId], [Result_2], []),
  'deleteTeam' : IDL.Func([IDL.Text, TeamId], [Result_2], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'generateRoundRobinFixtures' : IDL.Func([IDL.Text], [Result_4], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getBracket' : IDL.Func([], [IDL.Vec(BracketRoundView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeagueTable' : IDL.Func([], [IDL.Vec(LeagueRow)], ['query']),
  'getMatch' : IDL.Func([FixtureId], [IDL.Opt(MatchView)], ['query']),
  'getStatusMatches' : IDL.Func(
      [],
      [
        IDL.Record({
          'upcoming' : IDL.Vec(MatchView),
          'live' : IDL.Vec(MatchView),
          'completed' : IDL.Vec(MatchView),
        }),
      ],
      ['query'],
    ),
  'getTournamentState' : IDL.Func([], [TournamentState], ['query']),
  'isAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFixtures' : IDL.Func([], [IDL.Vec(Fixture)], ['query']),
  'listKnockoutTies' : IDL.Func([], [IDL.Vec(KnockoutTie)], ['query']),
  'listTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setFixtureResult' : IDL.Func(
      [IDL.Text, FixtureId, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), MatchStatus],
      [Result_1],
      [],
    ),
  'setKnockoutResult' : IDL.Func(
      [
        IDL.Text,
        TieId,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [Result_3],
      [],
    ),
  'setStageLabel' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'updateFixture' : IDL.Func(
      [IDL.Text, FixtureId, TeamId, TeamId, IDL.Nat, Timestamp],
      [Result_1],
      [],
    ),
  'updateTeam' : IDL.Func(
      [IDL.Text, TeamId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const AdminSession = IDL.Record({
    'token' : IDL.Text,
    'username' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TeamId = IDL.Nat;
  const Timestamp = IDL.Int;
  const FixtureId = IDL.Nat;
  const MatchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Fixture = IDL.Record({
    'id' : FixtureId,
    'status' : MatchStatus,
    'awayTeamId' : TeamId,
    'homeTeamId' : TeamId,
    'kickoff' : Timestamp,
    'homeGoals' : IDL.Opt(IDL.Nat),
    'matchday' : IDL.Nat,
    'awayGoals' : IDL.Opt(IDL.Nat),
  });
  const AdminError = IDL.Variant({
    'invalidInput' : IDL.Text,
    'notAuthenticated' : IDL.Null,
    'notFound' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : Fixture, 'err' : AdminError });
  const KnockoutRound = IDL.Variant({
    'final' : IDL.Null,
    'quarterFinal' : IDL.Null,
    'roundOf16' : IDL.Null,
    'semiFinal' : IDL.Null,
  });
  const TieId = IDL.Nat;
  const KnockoutTie = IDL.Record({
    'id' : TieId,
    'homePenalties' : IDL.Opt(IDL.Nat),
    'awayTeamId' : IDL.Opt(TeamId),
    'slot' : IDL.Nat,
    'awayPenalties' : IDL.Opt(IDL.Nat),
    'homeTeamId' : IDL.Opt(TeamId),
    'homeGoals' : IDL.Opt(IDL.Nat),
    'winnerTeamId' : IDL.Opt(TeamId),
    'awayGoals' : IDL.Opt(IDL.Nat),
    'round' : KnockoutRound,
  });
  const Result_3 = IDL.Variant({ 'ok' : KnockoutTie, 'err' : AdminError });
  const Team = IDL.Record({
    'id' : TeamId,
    'name' : IDL.Text,
    'crestUrl' : IDL.Opt(IDL.Text),
    'shortCode' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : Team, 'err' : AdminError });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AdminError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Vec(Fixture), 'err' : AdminError });
  const TieView = IDL.Record({
    'id' : TieId,
    'homePenalties' : IDL.Opt(IDL.Nat),
    'slot' : IDL.Nat,
    'awayTeamName' : IDL.Opt(IDL.Text),
    'awayPenalties' : IDL.Opt(IDL.Nat),
    'winnerTeamName' : IDL.Opt(IDL.Text),
    'homeTeamName' : IDL.Opt(IDL.Text),
    'homeGoals' : IDL.Opt(IDL.Nat),
    'awayGoals' : IDL.Opt(IDL.Nat),
    'round' : KnockoutRound,
  });
  const BracketRoundView = IDL.Record({
    'ties' : IDL.Vec(TieView),
    'round' : KnockoutRound,
  });
  const LeagueRow = IDL.Record({
    'won' : IDL.Nat,
    'teamName' : IDL.Text,
    'goalDifference' : IDL.Int,
    'played' : IDL.Nat,
    'lost' : IDL.Nat,
    'goalsFor' : IDL.Nat,
    'shortCode' : IDL.Text,
    'goalsAgainst' : IDL.Nat,
    'teamId' : TeamId,
    'drawn' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const MatchView = IDL.Record({
    'id' : FixtureId,
    'status' : MatchStatus,
    'awayTeamName' : IDL.Text,
    'homeTeamName' : IDL.Text,
    'kickoff' : Timestamp,
    'homeGoals' : IDL.Opt(IDL.Nat),
    'matchday' : IDL.Nat,
    'awayGoals' : IDL.Opt(IDL.Nat),
  });
  const TournamentState = IDL.Record({
    'tournamentName' : IDL.Text,
    'stageLabel' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_5], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(AdminSession)], []),
    'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFixture' : IDL.Func(
        [IDL.Text, TeamId, TeamId, IDL.Nat, Timestamp],
        [Result_1],
        [],
      ),
    'createKnockoutTie' : IDL.Func(
        [IDL.Text, KnockoutRound, IDL.Nat, IDL.Opt(TeamId), IDL.Opt(TeamId)],
        [Result_3],
        [],
      ),
    'createTeam' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'deleteFixture' : IDL.Func([IDL.Text, FixtureId], [Result_2], []),
    'deleteKnockoutTie' : IDL.Func([IDL.Text, TieId], [Result_2], []),
    'deleteTeam' : IDL.Func([IDL.Text, TeamId], [Result_2], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'generateRoundRobinFixtures' : IDL.Func([IDL.Text], [Result_4], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getBracket' : IDL.Func([], [IDL.Vec(BracketRoundView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeagueTable' : IDL.Func([], [IDL.Vec(LeagueRow)], ['query']),
    'getMatch' : IDL.Func([FixtureId], [IDL.Opt(MatchView)], ['query']),
    'getStatusMatches' : IDL.Func(
        [],
        [
          IDL.Record({
            'upcoming' : IDL.Vec(MatchView),
            'live' : IDL.Vec(MatchView),
            'completed' : IDL.Vec(MatchView),
          }),
        ],
        ['query'],
      ),
    'getTournamentState' : IDL.Func([], [TournamentState], ['query']),
    'isAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFixtures' : IDL.Func([], [IDL.Vec(Fixture)], ['query']),
    'listKnockoutTies' : IDL.Func([], [IDL.Vec(KnockoutTie)], ['query']),
    'listTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setFixtureResult' : IDL.Func(
        [IDL.Text, FixtureId, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), MatchStatus],
        [Result_1],
        [],
      ),
    'setKnockoutResult' : IDL.Func(
        [
          IDL.Text,
          TieId,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [Result_3],
        [],
      ),
    'setStageLabel' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'updateFixture' : IDL.Func(
        [IDL.Text, FixtureId, TeamId, TeamId, IDL.Nat, Timestamp],
        [Result_1],
        [],
      ),
    'updateTeam' : IDL.Func(
        [IDL.Text, TeamId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };