/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminError = { 'invalidInput' : string } |
  { 'notAuthenticated' : null } |
  { 'notFound' : null } |
  { 'invalidCredentials' : null };
export interface AdminSession { 'token' : string, 'username' : string }
export interface BracketRoundView {
  'ties' : Array<TieView>,
  'round' : KnockoutRound,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Fixture {
  'id' : FixtureId,
  'status' : MatchStatus,
  'awayTeamId' : TeamId,
  'homeTeamId' : TeamId,
  'kickoff' : Timestamp,
  'homeGoals' : [] | [bigint],
  'matchday' : bigint,
  'awayGoals' : [] | [bigint],
}
export type FixtureId = bigint;
export type KnockoutRound = { 'final' : null } |
  { 'quarterFinal' : null } |
  { 'roundOf16' : null } |
  { 'semiFinal' : null };
export interface KnockoutTie {
  'id' : TieId,
  'homePenalties' : [] | [bigint],
  'awayTeamId' : [] | [TeamId],
  'slot' : bigint,
  'awayPenalties' : [] | [bigint],
  'homeTeamId' : [] | [TeamId],
  'homeGoals' : [] | [bigint],
  'winnerTeamId' : [] | [TeamId],
  'awayGoals' : [] | [bigint],
  'round' : KnockoutRound,
}
export interface LeagueRow {
  'won' : bigint,
  'teamName' : string,
  'goalDifference' : bigint,
  'played' : bigint,
  'lost' : bigint,
  'goalsFor' : bigint,
  'shortCode' : string,
  'goalsAgainst' : bigint,
  'teamId' : TeamId,
  'drawn' : bigint,
  'points' : bigint,
}
export type MatchStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export interface MatchView {
  'id' : FixtureId,
  'status' : MatchStatus,
  'awayTeamName' : string,
  'homeTeamName' : string,
  'kickoff' : Timestamp,
  'homeGoals' : [] | [bigint],
  'matchday' : bigint,
  'awayGoals' : [] | [bigint],
}
export type Result = { 'ok' : Team } |
  { 'err' : AdminError };
export type Result_1 = { 'ok' : Fixture } |
  { 'err' : AdminError };
export type Result_2 = { 'ok' : null } |
  { 'err' : AdminError };
export type Result_3 = { 'ok' : KnockoutTie } |
  { 'err' : AdminError };
export type Result_4 = { 'ok' : Array<Fixture> } |
  { 'err' : AdminError };
export type Result_5 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Team {
  'id' : TeamId,
  'name' : string,
  'crestUrl' : [] | [string],
  'shortCode' : string,
}
export type TeamId = bigint;
export type TieId = bigint;
export interface TieView {
  'id' : TieId,
  'homePenalties' : [] | [bigint],
  'slot' : bigint,
  'awayTeamName' : [] | [string],
  'awayPenalties' : [] | [bigint],
  'winnerTeamName' : [] | [string],
  'homeTeamName' : [] | [string],
  'homeGoals' : [] | [bigint],
  'awayGoals' : [] | [bigint],
  'round' : KnockoutRound,
}
export type Timestamp = bigint;
export interface TournamentState {
  'tournamentName' : string,
  'stageLabel' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_5>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'adminLogin' : ActorMethod<[string, string], [] | [AdminSession]>,
  'adminLogout' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFixture' : ActorMethod<
    [string, TeamId, TeamId, bigint, Timestamp],
    Result_1
  >,
  'createKnockoutTie' : ActorMethod<
    [string, KnockoutRound, bigint, [] | [TeamId], [] | [TeamId]],
    Result_3
  >,
  'createTeam' : ActorMethod<[string, string, string, [] | [string]], Result>,
  'deleteFixture' : ActorMethod<[string, FixtureId], Result_2>,
  'deleteKnockoutTie' : ActorMethod<[string, TieId], Result_2>,
  'deleteTeam' : ActorMethod<[string, TeamId], Result_2>,
  'execute' : ActorMethod<[string], Result__1>,
  'generateRoundRobinFixtures' : ActorMethod<[string], Result_4>,
  'getApiDoc' : ActorMethod<[], string>,
  'getBracket' : ActorMethod<[], Array<BracketRoundView>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeagueTable' : ActorMethod<[], Array<LeagueRow>>,
  'getMatch' : ActorMethod<[FixtureId], [] | [MatchView]>,
  'getStatusMatches' : ActorMethod<
    [],
    {
      'upcoming' : Array<MatchView>,
      'live' : Array<MatchView>,
      'completed' : Array<MatchView>,
    }
  >,
  'getTournamentState' : ActorMethod<[], TournamentState>,
  'isAdminSession' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFixtures' : ActorMethod<[], Array<Fixture>>,
  'listKnockoutTies' : ActorMethod<[], Array<KnockoutTie>>,
  'listTeams' : ActorMethod<[], Array<Team>>,
  'schema' : ActorMethod<[], string>,
  'setFixtureResult' : ActorMethod<
    [string, FixtureId, [] | [bigint], [] | [bigint], MatchStatus],
    Result_1
  >,
  'setKnockoutResult' : ActorMethod<
    [string, TieId, [] | [bigint], [] | [bigint], [] | [bigint], [] | [bigint]],
    Result_3
  >,
  'setStageLabel' : ActorMethod<[string, string], Result_2>,
  'updateFixture' : ActorMethod<
    [string, FixtureId, TeamId, TeamId, bigint, Timestamp],
    Result_1
  >,
  'updateTeam' : ActorMethod<
    [string, TeamId, string, string, [] | [string]],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];