/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type AdminError = {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notAuthenticated";
    notAuthenticated: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "invalidCredentials";
    invalidCredentials: null;
};
export interface AdminSession {
    token: string;
    username: string;
}
export interface BracketRoundView {
    ties: Array<TieView>;
    round: KnockoutRound;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Fixture {
    id: FixtureId;
    status: MatchStatus;
    awayTeamId: TeamId;
    homeTeamId: TeamId;
    kickoff: Timestamp;
    homeGoals?: bigint;
    matchday: bigint;
    awayGoals?: bigint;
}
export type FixtureId = bigint;
export interface KnockoutTie {
    id: TieId;
    homePenalties?: bigint;
    awayTeamId?: TeamId;
    slot: bigint;
    awayPenalties?: bigint;
    homeTeamId?: TeamId;
    homeGoals?: bigint;
    winnerTeamId?: TeamId;
    awayGoals?: bigint;
    round: KnockoutRound;
}
export interface LeagueRow {
    won: bigint;
    teamName: string;
    goalDifference: bigint;
    played: bigint;
    lost: bigint;
    goalsFor: bigint;
    shortCode: string;
    goalsAgainst: bigint;
    teamId: TeamId;
    drawn: bigint;
    points: bigint;
}
export interface MatchView {
    id: FixtureId;
    status: MatchStatus;
    awayTeamName: string;
    homeTeamName: string;
    kickoff: Timestamp;
    homeGoals?: bigint;
    matchday: bigint;
    awayGoals?: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: Team;
} | {
    __kind__: "err";
    err: AdminError;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Fixture;
} | {
    __kind__: "err";
    err: AdminError;
};
export type Result_2 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AdminError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: KnockoutTie;
} | {
    __kind__: "err";
    err: AdminError;
};
export type Result_4 = {
    __kind__: "ok";
    ok: Array<Fixture>;
} | {
    __kind__: "err";
    err: AdminError;
};
export type Result_5 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Team {
    id: TeamId;
    name: string;
    crestUrl?: string;
    shortCode: string;
}
export type TeamId = bigint;
export type TieId = bigint;
export interface TieView {
    id: TieId;
    homePenalties?: bigint;
    slot: bigint;
    awayTeamName?: string;
    awayPenalties?: bigint;
    winnerTeamName?: string;
    homeTeamName?: string;
    homeGoals?: bigint;
    awayGoals?: bigint;
    round: KnockoutRound;
}
export type Timestamp = bigint;
export interface TournamentState {
    tournamentName: string;
    stageLabel: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum KnockoutRound {
    final = "final",
    quarterFinal = "quarterFinal",
    roundOf16 = "roundOf16",
    semiFinal = "semiFinal"
}
export enum MatchStatus {
    upcoming = "upcoming",
    live = "live",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_5>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    adminLogin(username: string, password: string): Promise<AdminSession | null>;
    adminLogout(token: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFixture(token: string, homeTeamId: TeamId, awayTeamId: TeamId, matchday: bigint, kickoff: Timestamp): Promise<Result_1>;
    createKnockoutTie(token: string, round: KnockoutRound, slot: bigint, homeTeamId: TeamId | null, awayTeamId: TeamId | null): Promise<Result_3>;
    createTeam(token: string, name: string, shortCode: string, crestUrl: string | null): Promise<Result>;
    deleteFixture(token: string, id: FixtureId): Promise<Result_2>;
    deleteKnockoutTie(token: string, id: TieId): Promise<Result_2>;
    deleteTeam(token: string, id: TeamId): Promise<Result_2>;
    execute(qJson: string): Promise<Result__1>;
    generateRoundRobinFixtures(token: string): Promise<Result_4>;
    getApiDoc(): Promise<string>;
    getBracket(): Promise<Array<BracketRoundView>>;
    getCallerUserRole(): Promise<UserRole>;
    getLeagueTable(): Promise<Array<LeagueRow>>;
    getMatch(id: FixtureId): Promise<MatchView | null>;
    getStatusMatches(): Promise<{
        upcoming: Array<MatchView>;
        live: Array<MatchView>;
        completed: Array<MatchView>;
    }>;
    getTournamentState(): Promise<TournamentState>;
    isAdminSession(token: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listFixtures(): Promise<Array<Fixture>>;
    listKnockoutTies(): Promise<Array<KnockoutTie>>;
    listTeams(): Promise<Array<Team>>;
    schema(): Promise<string>;
    setFixtureResult(token: string, id: FixtureId, homeGoals: bigint | null, awayGoals: bigint | null, status: MatchStatus): Promise<Result_1>;
    setKnockoutResult(token: string, id: TieId, homeGoals: bigint | null, awayGoals: bigint | null, homePenalties: bigint | null, awayPenalties: bigint | null): Promise<Result_3>;
    setStageLabel(token: string, stageLabel: string): Promise<Result_2>;
    updateFixture(token: string, id: FixtureId, homeTeamId: TeamId, awayTeamId: TeamId, matchday: bigint, kickoff: Timestamp): Promise<Result_1>;
    updateTeam(token: string, id: TeamId, name: string, shortCode: string, crestUrl: string | null): Promise<Result>;
}
import type { AdminError as _AdminError, AdminSession as _AdminSession, BracketRoundView as _BracketRoundView, Cell as _Cell, Error as _Error, Fixture as _Fixture, FixtureId as _FixtureId, KnockoutRound as _KnockoutRound, KnockoutTie as _KnockoutTie, MatchStatus as _MatchStatus, MatchView as _MatchView, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result__1 as _Result__1, Team as _Team, TeamId as _TeamId, TieId as _TieId, TieView as _TieView, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_5_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_5_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<AdminSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFixture(arg0: string, arg1: TeamId, arg2: TeamId, arg3: bigint, arg4: Timestamp): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createFixture(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFixture(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createKnockoutTie(arg0: string, arg1: KnockoutRound, arg2: bigint, arg3: TeamId | null, arg4: TeamId | null): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.createKnockoutTie(arg0, to_candid_KnockoutRound_n15(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_3_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createKnockoutTie(arg0, to_candid_KnockoutRound_n15(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_3_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTeam(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(arg0, arg1, arg2, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(arg0, arg1, arg2, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFixture(arg0: string, arg1: FixtureId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFixture(arg0, arg1);
                return from_candid_Result_2_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFixture(arg0, arg1);
            return from_candid_Result_2_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteKnockoutTie(arg0: string, arg1: TieId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKnockoutTie(arg0, arg1);
                return from_candid_Result_2_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKnockoutTie(arg0, arg1);
            return from_candid_Result_2_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTeam(arg0: string, arg1: TeamId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeam(arg0, arg1);
                return from_candid_Result_2_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeam(arg0, arg1);
            return from_candid_Result_2_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateRoundRobinFixtures(arg0: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.generateRoundRobinFixtures(arg0);
                return from_candid_Result_4_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateRoundRobinFixtures(arg0);
            return from_candid_Result_4_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getBracket(): Promise<Array<BracketRoundView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBracket();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBracket();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeagueTable(): Promise<Array<LeagueRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeagueTable();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeagueTable();
            return result;
        }
    }
    async getMatch(arg0: FixtureId): Promise<MatchView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatusMatches(): Promise<{
        upcoming: Array<MatchView>;
        live: Array<MatchView>;
        completed: Array<MatchView>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatusMatches();
                return from_candid_record_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatusMatches();
            return from_candid_record_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentState(): Promise<TournamentState> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentState();
            return result;
        }
    }
    async isAdminSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminSession(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFixtures(): Promise<Array<Fixture>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFixtures();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFixtures();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listKnockoutTies(): Promise<Array<KnockoutTie>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKnockoutTies();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKnockoutTies();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeams();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeams();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setFixtureResult(arg0: string, arg1: FixtureId, arg2: bigint | null, arg3: bigint | null, arg4: MatchStatus): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.setFixtureResult(arg0, arg1, to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg3), to_candid_MatchStatus_n57(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFixtureResult(arg0, arg1, to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg3), to_candid_MatchStatus_n57(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async setKnockoutResult(arg0: string, arg1: TieId, arg2: bigint | null, arg3: bigint | null, arg4: bigint | null, arg5: bigint | null): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.setKnockoutResult(arg0, arg1, to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Result_3_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setKnockoutResult(arg0, arg1, to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Result_3_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStageLabel(arg0: string, arg1: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.setStageLabel(arg0, arg1);
                return from_candid_Result_2_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStageLabel(arg0, arg1);
            return from_candid_Result_2_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFixture(arg0: string, arg1: FixtureId, arg2: TeamId, arg3: TeamId, arg4: bigint, arg5: Timestamp): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFixture(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFixture(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTeam(arg0: string, arg1: TeamId, arg2: string, arg3: string, arg4: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeam(arg0, arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeam(arg0, arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminError_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminError): AdminError {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_BracketRoundView_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BracketRoundView): BracketRoundView {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Fixture_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fixture): Fixture {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_KnockoutRound_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnockoutRound): KnockoutRound {
    return "final" in value ? KnockoutRound.final : "quarterFinal" in value ? KnockoutRound.quarterFinal : "roundOf16" in value ? KnockoutRound.roundOf16 : "semiFinal" in value ? KnockoutRound.semiFinal : value;
}
function from_candid_KnockoutTie_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnockoutTie): KnockoutTie {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return "upcoming" in value ? MatchStatus.upcoming : "live" in value ? MatchStatus.live : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_MatchView_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchView): MatchView {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TieView_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TieView): TieView {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamId]): TeamId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchView]): MatchView | null {
    return value.length === 0 ? null : from_candid_MatchView_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminSession]): AdminSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FixtureId;
    status: _MatchStatus;
    awayTeamId: _TeamId;
    homeTeamId: _TeamId;
    kickoff: _Timestamp;
    homeGoals: [] | [bigint];
    matchday: bigint;
    awayGoals: [] | [bigint];
}): {
    id: FixtureId;
    status: MatchStatus;
    awayTeamId: TeamId;
    homeTeamId: TeamId;
    kickoff: Timestamp;
    homeGoals?: bigint;
    matchday: bigint;
    awayGoals?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n11(_uploadFile, _downloadFile, value.status),
        awayTeamId: value.awayTeamId,
        homeTeamId: value.homeTeamId,
        kickoff: value.kickoff,
        homeGoals: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.homeGoals)),
        matchday: value.matchday,
        awayGoals: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.awayGoals))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TieId;
    homePenalties: [] | [bigint];
    awayTeamId: [] | [_TeamId];
    slot: bigint;
    awayPenalties: [] | [bigint];
    homeTeamId: [] | [_TeamId];
    homeGoals: [] | [bigint];
    winnerTeamId: [] | [_TeamId];
    awayGoals: [] | [bigint];
    round: _KnockoutRound;
}): {
    id: TieId;
    homePenalties?: bigint;
    awayTeamId?: TeamId;
    slot: bigint;
    awayPenalties?: bigint;
    homeTeamId?: TeamId;
    homeGoals?: bigint;
    winnerTeamId?: TeamId;
    awayGoals?: bigint;
    round: KnockoutRound;
} {
    return {
        id: value.id,
        homePenalties: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.homePenalties)),
        awayTeamId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.awayTeamId)),
        slot: value.slot,
        awayPenalties: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.awayPenalties)),
        homeTeamId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.homeTeamId)),
        homeGoals: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.homeGoals)),
        winnerTeamId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.winnerTeamId)),
        awayGoals: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.awayGoals)),
        round: from_candid_KnockoutRound_n22(_uploadFile, _downloadFile, value.round)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TeamId;
    name: string;
    crestUrl: [] | [string];
    shortCode: string;
}): {
    id: TeamId;
    name: string;
    crestUrl?: string;
    shortCode: string;
} {
    return {
        id: value.id,
        name: value.name,
        crestUrl: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.crestUrl)),
        shortCode: value.shortCode
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n33(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n37(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ties: Array<_TieView>;
    round: _KnockoutRound;
}): {
    ties: Array<TieView>;
    round: KnockoutRound;
} {
    return {
        ties: from_candid_vec_n45(_uploadFile, _downloadFile, value.ties),
        round: from_candid_KnockoutRound_n22(_uploadFile, _downloadFile, value.round)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TieId;
    homePenalties: [] | [bigint];
    slot: bigint;
    awayTeamName: [] | [string];
    awayPenalties: [] | [bigint];
    winnerTeamName: [] | [string];
    homeTeamName: [] | [string];
    homeGoals: [] | [bigint];
    awayGoals: [] | [bigint];
    round: _KnockoutRound;
}): {
    id: TieId;
    homePenalties?: bigint;
    slot: bigint;
    awayTeamName?: string;
    awayPenalties?: bigint;
    winnerTeamName?: string;
    homeTeamName?: string;
    homeGoals?: bigint;
    awayGoals?: bigint;
    round: KnockoutRound;
} {
    return {
        id: value.id,
        homePenalties: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.homePenalties)),
        slot: value.slot,
        awayTeamName: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.awayTeamName)),
        awayPenalties: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.awayPenalties)),
        winnerTeamName: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.winnerTeamName)),
        homeTeamName: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.homeTeamName)),
        homeGoals: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.homeGoals)),
        awayGoals: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.awayGoals)),
        round: from_candid_KnockoutRound_n22(_uploadFile, _downloadFile, value.round)
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FixtureId;
    status: _MatchStatus;
    awayTeamName: string;
    homeTeamName: string;
    kickoff: _Timestamp;
    homeGoals: [] | [bigint];
    matchday: bigint;
    awayGoals: [] | [bigint];
}): {
    id: FixtureId;
    status: MatchStatus;
    awayTeamName: string;
    homeTeamName: string;
    kickoff: Timestamp;
    homeGoals?: bigint;
    matchday: bigint;
    awayGoals?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n11(_uploadFile, _downloadFile, value.status),
        awayTeamName: value.awayTeamName,
        homeTeamName: value.homeTeamName,
        kickoff: value.kickoff,
        homeGoals: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.homeGoals)),
        matchday: value.matchday,
        awayGoals: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.awayGoals))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: Array<_MatchView>;
    live: Array<_MatchView>;
    completed: Array<_MatchView>;
}): {
    upcoming: Array<MatchView>;
    live: Array<MatchView>;
    completed: Array<MatchView>;
} {
    return {
        upcoming: from_candid_vec_n53(_uploadFile, _downloadFile, value.upcoming),
        live: from_candid_vec_n53(_uploadFile, _downloadFile, value.live),
        completed: from_candid_vec_n53(_uploadFile, _downloadFile, value.completed)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidInput: string;
} | {
    notAuthenticated: null;
} | {
    notFound: null;
} | {
    invalidCredentials: null;
}): {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notAuthenticated";
    notAuthenticated: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "invalidCredentials";
    invalidCredentials: null;
} {
    return "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "notAuthenticated" in value ? {
        __kind__: "notAuthenticated",
        notAuthenticated: value.notAuthenticated
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "invalidCredentials" in value ? {
        __kind__: "invalidCredentials",
        invalidCredentials: value.invalidCredentials
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _KnockoutTie;
} | {
    err: _AdminError;
}): {
    __kind__: "ok";
    ok: KnockoutTie;
} | {
    __kind__: "err";
    err: AdminError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_KnockoutTie_n19(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AdminError_n13(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Team;
} | {
    err: _AdminError;
}): {
    __kind__: "ok";
    ok: Team;
} | {
    __kind__: "err";
    err: AdminError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Team_n26(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AdminError_n13(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _AdminError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AdminError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AdminError_n13(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Fixture>;
} | {
    err: _AdminError;
}): {
    __kind__: "ok";
    ok: Array<Fixture>;
} | {
    __kind__: "err";
    err: AdminError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n41(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AdminError_n13(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Fixture;
} | {
    err: _AdminError;
}): {
    __kind__: "ok";
    ok: Fixture;
} | {
    __kind__: "err";
    err: AdminError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Fixture_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AdminError_n13(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fixture>): Array<Fixture> {
    return value.map((x)=>from_candid_Fixture_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BracketRoundView>): Array<BracketRoundView> {
    return value.map((x)=>from_candid_BracketRoundView_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TieView>): Array<TieView> {
    return value.map((x)=>from_candid_TieView_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchView>): Array<MatchView> {
    return value.map((x)=>from_candid_MatchView_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KnockoutTie>): Array<KnockoutTie> {
    return value.map((x)=>from_candid_KnockoutTie_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n26(_uploadFile, _downloadFile, x));
}
function to_candid_KnockoutRound_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KnockoutRound): _KnockoutRound {
    return value == KnockoutRound.final ? {
        final: null
    } : value == KnockoutRound.quarterFinal ? {
        quarterFinal: null
    } : value == KnockoutRound.roundOf16 ? {
        roundOf16: null
    } : value == KnockoutRound.semiFinal ? {
        semiFinal: null
    } : value;
}
function to_candid_MatchStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): _MatchStatus {
    return value == MatchStatus.upcoming ? {
        upcoming: null
    } : value == MatchStatus.live ? {
        live: null
    } : value == MatchStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamId | null): [] | [_TeamId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
